// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type StoryListElem struct {
	react.Element
}

func buildStoryList(cd react.ComponentDef) react.Component {
	return StoryListDef{ComponentDef: cd}
}

func buildStoryListElem(props StoryListProps, children ...react.Element) *StoryListElem {
	return &StoryListElem{
		Element: react.CreateElement(buildStoryList, props, children...),
	}
}

func (s StoryListDef) RendersElement() react.Element {
	return s.Render()
}

// IsProps is an auto-generated definition so that StoryListProps implements
// the myitcv.io/react.Props interface.
func (s StoryListProps) IsProps() {}

// Props is an auto-generated proxy to the current props of StoryList
func (s StoryListDef) Props() StoryListProps {
	uprops := s.ComponentDef.Props()
	return uprops.(StoryListProps)
}

func (s StoryListProps) EqualsIntf(val react.Props) bool {
	return s.Equals(val.(StoryListProps))
}

var _ react.Props = StoryListProps{}
