// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type StoryCardElem struct {
	react.Element
}

func (s *StoryCardElem) RendersLi(*react.LiElem) {}

func (s *StoryCardElem) noop() {
	var v StoryCardDef
	r := v.Render()

	v.RendersLi(r)
}

func buildStoryCard(cd react.ComponentDef) react.Component {
	return StoryCardDef{ComponentDef: cd}
}

func buildStoryCardElem(props StoryCardProps, children ...react.Element) *StoryCardElem {
	return &StoryCardElem{
		Element: react.CreateElement(buildStoryCard, props, children...),
	}
}

func (s StoryCardDef) RendersElement() react.Element {
	return s.Render()
}

// IsProps is an auto-generated definition so that StoryCardProps implements
// the myitcv.io/react.Props interface.
func (s StoryCardProps) IsProps() {}

// Props is an auto-generated proxy to the current props of StoryCard
func (s StoryCardDef) Props() StoryCardProps {
	uprops := s.ComponentDef.Props()
	return uprops.(StoryCardProps)
}

func (s StoryCardProps) EqualsIntf(val react.Props) bool {
	return s == val.(StoryCardProps)
}

var _ react.Props = StoryCardProps{}
