// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type PageNavElem struct {
	react.Element
}

func buildPageNav(cd react.ComponentDef) react.Component {
	return PageNavDef{ComponentDef: cd}
}

func buildPageNavElem(props PageNavProps, children ...react.Element) *PageNavElem {
	return &PageNavElem{
		Element: react.CreateElement(buildPageNav, props, children...),
	}
}

func (p PageNavDef) RendersElement() react.Element {
	return p.Render()
}

// IsProps is an auto-generated definition so that PageNavProps implements
// the myitcv.io/react.Props interface.
func (p PageNavProps) IsProps() {}

// Props is an auto-generated proxy to the current props of PageNav
func (p PageNavDef) Props() PageNavProps {
	uprops := p.ComponentDef.Props()
	return uprops.(PageNavProps)
}

func (p PageNavProps) EqualsIntf(val react.Props) bool {
	return p == val.(PageNavProps)
}

var _ react.Props = PageNavProps{}
